---
# file: tasks/install-git-tools.yml
# Top-level installer tools required for compiling Prometheus sources.
#
# @see https://github.com/prometheus/prometheus
#

- name: install dependencies for installation of components from source
  yum:
    name: ['git','gzip','curl','make']
    update_cache: yes
    state: present
  become: true

- name: set internal variables for convenience
  set_fact:
    prometheus_golang_tarball_url: "https://storage.googleapis.com/golang/go{{ prometheus_go_version }}.linux-amd64.tar.gz"

- name: mkdir for Golang
  file: path={{ item }}  state=directory
  with_items:
    - "{{ prometheus_goroot }}"
    - "{{ prometheus_gopath }}"
  become: true

- name: download and untar Golang tarball
  unarchive:
    src:  "{{ prometheus_golang_tarball_url }}"
    dest: "{{ prometheus_workdir }}"
    copy: no
    creates: "{{ prometheus_goroot }}/bin/go"
  become: true
